apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flx-plugin
  namespace: felix
  labels:
    app: flx-plugin
spec:
  selector:
    matchLabels:
      name: flx-plugin
  template:
    metadata:
      labels:
        name: flx-plugin
    spec:
      initContainers:
      - name: flx-driver
        image: np04docker.cern.ch/dunedaq-local/flx-driver:v0.3
        securityContext:
          privileged: true
        volumeMounts:
          - name: devfs
            mountPath: /dev
          - name: opt
            mountPath: /opt/felix/drivers_rcc
            readOnly: true
      containers:
      - name: flx-plugin
        image: np04docker.cern.ch/dunedaq-local/flx-plugin:v0.3
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: devfs
          mountPath: /dev
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: opt
        hostPath:
          path: /opt/felix/drivers_rcc
        

