name: Build k8s device plugin image

on:
  schedule:
    - cron: "0 5 * * 2"

  push:
    branches: [ develop ]
    tags:
      - 'v*'
    paths:
      - flx-plugin/Dockerfile

  workflow_dispatch:

jobs:

  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          repository: DUNE-DAQ/flx-k8s-device-plugin
          path: flx-k8s-device-plugin 
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/DUNE-DAQ/flx-device-plugin
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=tag

      - name: prepare build dir
        run: |
          build_dir="${{ github.workspace }}/docker-build"
          mkdir -p $build_dir
          cd $build_dir
          cp ${{ github.workspace }}/flx-k8s-device-plugin/flx-plugin/Dockerfile $build_dir/Dockerfile
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}/docker-build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
